version: '3.8'

services:
  db: 
    image: mongo
    container_name: db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=vini
      - MONGO_INITDB_ROOT_PASSWORD=vini
    ports:
      -"27017:27017"
    volumes:
      -F:\Tecnologia da Informação\BootCamp XP\DataBases\mongo-db:data\db
    